-- AlterTable
ALTER TABLE "Payment" ADD COLUMN IF NOT EXISTS "providerRefundId" TEXT;
ALTER TABLE "Payment" ADD COLUMN IF NOT EXISTS "refundedAmount" DECIMAL(10,2) NOT NULL DEFAULT 0;
ALTER TABLE "Payment" ADD COLUMN IF NOT EXISTS "refundedAt" TIMESTAMP(3);
